name: "Run black formatter"
description: "Run the black formatter on your codebase to improve code review experience."
author: "Khoa Nguyen"
inputs:
  black_args:
    description: "Black input arguments."
    required: false
    default: ""
  fail_on_error:
    description: |
      Exit code when black formatting errors are found [true, false]. Defaults to 'true'.
    required: false
    default: "true"
outputs:
  is_formatted:
    description: "Whether the files were formatted using the black formatter."
branding:
  color: "black"
  icon: "check-circle"
runs:
  using: "composite"
  steps:
    - run: echo "Black Linting is called"