version: "3.7"
services:
    jenkins:
        image: jenkins/jenkins:jdk17
        container_name: jenkins
        hostname: jenkins
        ports:
            - "0.0.0.0:8080:8080"
            - "0.0.0.0:50000:50000"
        volumes:
            - ./dev_data/jenkins_home:/var/jenkins_home
        dns:
            - "8.8.8.8"
            - "8.8.4.4"
    cloudflare:
        image: cloudflare/cloudflared:latest
        container_name: cloudflare
        hostname: cloudflare
        command: "tunnel --no-autoupdate run"
        environment:
            - TUNNEL_TOKEN=eyJhIjoiNTI5MGQxMDZkNjE5NjliY2E4YTZlOGM4ODc2OTJlYmIiLCJ0IjoiYjJhMTg0MTAtYTRjYy00YWEyLWEzZjctZDUyNjJiMDBlZDRiIiwicyI6Ik1qUXdOV0ptT0RjdE4yTmlPUzAwTVRnNUxXSXpOemN0TnpBek5USmlORE5rTWpWaCJ9
    registry:
        image: registry:2.8.3
        container_name: registry
        hostname: registry
        ports:
            - "0.0.0.0:5000:5000"