name: Python Linting Workflow
run-name: Black linter is working 🚀
on: [push]
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - name: My first step - check out repository
        uses: actions/checkout@v4
      # This step references the directory that contains the action.
#      - name: Grant execute permission for entrypoint.sh file
#        using: "docker"
#        image: "./black/Dockerfile"
      - name: Run ls -l command
        run: ls -l
      - name: Run Black Linter from repo
        uses: ./.github/actions/black_linter
